services:
  frp_client:
    image: svgitlab.benhvien.tech:5005/elsaga/srl/frp:latest
    command: /work/frp/frpc -c /data/frpc.toml
    environment:
      - HOST_IP=${HOST_IP}
      - FRP_TOKEN=${FRP_TOKEN}
    restart: always
    #ports:
    #  - 2222:22
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #network_mode: host
    volumes:
      - ./frpc.toml:/data/frpc.toml
